// theme.js — Shared Tailwind design tokens for the Yearbook 2026 binder site.
// Load this once (right after the Tailwind CDN script) on every page instead
// of repeating the same ~80-line config block in each HTML file.
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#8fe7c6",
        "error-container": "#ffdad6",
        "washi-tape-pink": "#ff9fcb",
        "tertiary-fixed-dim": "#82d2f6",
        "surface-container": "#fff7df",
        "surface-container-low": "#fffaf0",
        "surface-bright": "#fffdf4",
        surface: "#fffaf0",
        "on-primary-fixed": "#3d0024",
        "on-tertiary-fixed": "#001e2c",
        "sticker-shadow": "#000000",
        "on-secondary": "#ffffff",
        "tertiary-container": "#00668a",
        "paper-background": "#fcfae4",
        "surface-tint": "#ac2471",
        "outline-variant": "#dcbfc9",
        "surface-container-highest": "#f1ead6",
        "paper-grid-dot": "#8bb2d4",
        tertiary: "#006b85",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#ac2471",
        "secondary-container": "#9df4d2",
        "on-tertiary-container": "#ace0ff",
        "surface-variant": "#e5e3ce",
        "on-primary": "#ffffff",
        "surface-container-high": "#ebe9d4",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f4f2dc",
        "primary-fixed-dim": "#ffb4d6",
        "inverse-surface": "#313123",
        "on-surface": "#20212f",
        "on-error": "#ffffff",
        "surface-dim": "#f1e8d7",
        background: "#fffaf0",
        "tertiary-fixed": "#bfe8ff",
        "secondary-fixed-dim": "#63cfaa",
        "on-primary-container": "#ffcade",
        outline: "#897179",
        "on-background": "#1c1c0f",
        "on-surface-variant": "#4b5570",
        primary: "#0d78a8",
        "on-tertiary-fixed-variant": "#004c68",
        error: "#ba1a1a",
        secondary: "#f07035",
        "on-secondary-fixed-variant": "#00513d",
        "inverse-primary": "#ffafd0",
        "paper-rule-line": "#aac7e8",
        "on-secondary-container": "#6d2d00",
        "on-secondary-fixed": "#002117",
        "on-primary-fixed-variant": "#8b0058",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d7efff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        "display-script": ["Epilogue"],
        "display-lg": ["Bricolage Grotesque"],
        "body-lg": ["Space Grotesk"],
        "headline-lg": ["Bricolage Grotesque"],
        "label-sm": ["JetBrains Mono"],
        handwriting: ["Indie Flower"],
      },
      fontSize: {
        "display-script": ["48px", { lineHeight: "52px", fontWeight: "300" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "44px", fontWeight: "700" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0", fontWeight: "500" },
        ],
        "display-lg": [
          "84px",
          { lineHeight: "80px", letterSpacing: "0", fontWeight: "800" },
        ],
      },
    },
  },
};
